-- Run this in Supabase SQL Editor to create missing tables
-- Go to: https://app.supabase.com → SQL Editor → New Query → Paste this → Run

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE,
  account_type TEXT,
  role TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DRIVER_SUBMISSIONS TABLE
CREATE TABLE IF NOT EXISTS driver_submissions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  submission_type TEXT NOT NULL,
  submission_data JSONB,
  status TEXT DEFAULT 'pending',
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approved_by BIGINT,
  approved_at TIMESTAMP,
  rejection_reason TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RENT_TO_OWN_AGREEMENTS TABLE
CREATE TABLE IF NOT EXISTS rent_to_own_agreements (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  vehicle_id BIGINT REFERENCES vehicles(id),
  quotation_id BIGINT REFERENCES quotations(id),
  total_amount DECIMAL(12, 2),
  paid_amount DECIMAL(12, 2) DEFAULT 0,
  remaining_balance DECIMAL(12, 2),
  agreement_status TEXT DEFAULT 'Active',
  ownership_transferred BOOLEAN DEFAULT FALSE,
  ownership_transferred_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RENT_TO_OWN_PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS rent_to_own_payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agreement_id BIGINT NOT NULL REFERENCES rent_to_own_agreements(id) ON DELETE CASCADE,
  amount_paid DECIMAL(12, 2),
  payment_date TIMESTAMP,
  recorded_by TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT_CATEGORIES TABLE (for weekly cash vs rent-to-own tracking)
CREATE TABLE IF NOT EXISTS payment_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_id BIGINT REFERENCES payments(id) ON DELETE CASCADE,
  driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE,
  category_type TEXT, -- 'weekly_cash' or 'rent_to_own'
  rent_to_own_agreement_id BIGINT REFERENCES rent_to_own_agreements(id),
  amount DECIMAL(12, 2),
  payment_date TIMESTAMP,
  is_backdated BOOLEAN DEFAULT FALSE,
  backdated_for_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT BACKDATING TABLE (for historical payments)
CREATE TABLE IF NOT EXISTS payment_backdating (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  payment_date TIMESTAMP NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  category_type TEXT, -- 'weekly_cash' or 'rent_to_own'
  rent_to_own_agreement_id BIGINT REFERENCES rent_to_own_agreements(id),
  description TEXT,
  recorded_by TEXT,
  is_applied BOOLEAN DEFAULT FALSE,
  applied_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ADD MISSING COLUMNS TO EXISTING TABLES

-- Add columns to quotations if missing
ALTER TABLE quotations
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add payment_type column to payments table
ALTER TABLE payments
ADD COLUMN IF NOT EXISTS payment_type TEXT DEFAULT 'weekly_cash', -- 'weekly_cash' or 'rent_to_own'
ADD COLUMN IF NOT EXISTS rent_to_own_agreement_id BIGINT REFERENCES rent_to_own_agreements(id),
ADD COLUMN IF NOT EXISTS is_backdated BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS backdated_for_date TIMESTAMP;

-- Enable RLS if not already enabled
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE rent_to_own_agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE rent_to_own_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_backdating ENABLE ROW LEVEL SECURITY;

-- Create basic RLS policies
CREATE POLICY "Enable read for authenticated users" ON users FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable read for authenticated users" ON driver_submissions FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable read for authenticated users" ON rent_to_own_agreements FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable read for authenticated users" ON rent_to_own_payments FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable read for authenticated users" ON payment_categories FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable read for authenticated users" ON payment_backdating FOR SELECT USING (auth.role() = 'authenticated');

-- Success message
SELECT 'All tables created/updated successfully!' as status;
