-- BLACKBIRD ERP - Complete Supabase Schema with All Fixes
-- Run this in Supabase SQL Editor

-- ========================================
-- DROP AND RECREATE WITH CORRECT SETTINGS
-- ========================================

-- First, backup existing data if needed
-- Then recreate with GENERATED BY DEFAULT AS IDENTITY

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE,
  account_type TEXT,
  role TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DRIVERS TABLE - FIX ID COLUMN
DROP TABLE IF EXISTS drivers CASCADE;
CREATE TABLE drivers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  phone TEXT,
  national_id TEXT,
  license_number TEXT,
  plate TEXT,
  type TEXT,
  status TEXT DEFAULT 'Active',
  assigned_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- VEHICLES TABLE - FIX ID COLUMN
DROP TABLE IF EXISTS vehicles CASCADE;
CREATE TABLE vehicles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  plate TEXT UNIQUE,
  type TEXT,
  make_model TEXT,
  assigned_driver_id BIGINT REFERENCES drivers(id),
  vehicle_condition TEXT,
  road_tax_due TEXT,
  insurance_due TEXT,
  service_due_km TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- QUOTATIONS TABLE - FIX ID COLUMN
DROP TABLE IF EXISTS quotations CASCADE;
CREATE TABLE quotations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  quote_number TEXT UNIQUE,
  client_name TEXT,
  quote_date TIMESTAMP,
  items JSONB,
  total_amount DECIMAL(12, 2),
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INVOICES TABLE - FIX ID COLUMN
DROP TABLE IF EXISTS invoices CASCADE;
CREATE TABLE invoices (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_number TEXT UNIQUE,
  client_name TEXT,
  invoice_date TIMESTAMP,
  items JSONB,
  total_amount DECIMAL(12, 2),
  status TEXT DEFAULT 'unpaid',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENTS TABLE - FIX ID COLUMN AND ADD driver_id
DROP TABLE IF EXISTS payments CASCADE;
CREATE TABLE payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_date TIMESTAMP,
  payer_name TEXT,
  payment_type TEXT DEFAULT 'weekly_cash',
  amount DECIMAL(12, 2),
  week INTEGER,
  payment_status TEXT DEFAULT 'Paid',
  description TEXT,
  driver_id INTEGER REFERENCES drivers(id),
  rent_to_own_agreement_id BIGINT,
  is_backdated BOOLEAN DEFAULT FALSE,
  backdated_for_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- JOBS TABLE - FIX ID COLUMN
DROP TABLE IF EXISTS jobs CASCADE;
CREATE TABLE jobs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  job_title TEXT,
  description TEXT,
  status TEXT DEFAULT 'open',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DRIVER_SUBMISSIONS TABLE
CREATE TABLE IF NOT EXISTS driver_submissions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  submission_type TEXT NOT NULL,
  submission_data JSONB,
  status TEXT DEFAULT 'pending',
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approved_by BIGINT,
  approved_at TIMESTAMP,
  rejection_reason TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RENT_TO_OWN_AGREEMENTS TABLE
CREATE TABLE IF NOT EXISTS rent_to_own_agreements (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  vehicle_id BIGINT REFERENCES vehicles(id),
  quotation_id BIGINT REFERENCES quotations(id),
  total_amount DECIMAL(12, 2),
  paid_amount DECIMAL(12, 2) DEFAULT 0,
  remaining_balance DECIMAL(12, 2),
  agreement_status TEXT DEFAULT 'Active',
  ownership_transferred BOOLEAN DEFAULT FALSE,
  ownership_transferred_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RENT_TO_OWN_PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS rent_to_own_payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agreement_id BIGINT NOT NULL REFERENCES rent_to_own_agreements(id) ON DELETE CASCADE,
  amount_paid DECIMAL(12, 2),
  payment_date TIMESTAMP,
  recorded_by TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT_CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS payment_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_id BIGINT REFERENCES payments(id) ON DELETE CASCADE,
  driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE,
  category_type TEXT,
  rent_to_own_agreement_id BIGINT REFERENCES rent_to_own_agreements(id),
  amount DECIMAL(12, 2),
  payment_date TIMESTAMP,
  is_backdated BOOLEAN DEFAULT FALSE,
  backdated_for_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT BACKDATING TABLE
CREATE TABLE IF NOT EXISTS payment_backdating (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  payment_date TIMESTAMP NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  category_type TEXT,
  rent_to_own_agreement_id BIGINT REFERENCES rent_to_own_agreements(id),
  description TEXT,
  recorded_by TEXT,
  is_applied BOOLEAN DEFAULT FALSE,
  applied_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- WEBSITE_VISITS TABLE (if needed)
CREATE TABLE IF NOT EXISTS website_visits (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  page_url TEXT,
  visitor_ip TEXT,
  visited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_agent TEXT,
  referrer TEXT
);

-- ========================================
-- ENABLE ROW LEVEL SECURITY (Optional but recommended)
-- ========================================

-- Enable RLS for security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE rent_to_own_agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE rent_to_own_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_backdating ENABLE ROW LEVEL SECURITY;

-- Allow all for anon (for now - secure later)
CREATE POLICY "Allow all for anon" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON drivers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON vehicles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON payments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON quotations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON invoices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON jobs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON driver_submissions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON rent_to_own_agreements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON rent_to_own_payments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON payment_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON payment_backdating FOR ALL USING (true) WITH CHECK (true);

SELECT 'All tables created with GENERATED BY DEFAULT AS IDENTITY!' as status;
