-- BLACKBIRD ERP - Safe Fixes for Supabase (Preserves All Data)
-- Run this in Supabase SQL Editor one statement at a time

-- ========================================
-- FIX ID COLUMNS TO ALLOW INSERT
-- ========================================

-- Fix drivers table
ALTER TABLE drivers ALTER COLUMN id DROP IDENTITY;
ALTER TABLE drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix vehicles table
ALTER TABLE vehicles ALTER COLUMN id DROP IDENTITY;
ALTER TABLE vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix quotations table
ALTER TABLE quotations ALTER COLUMN id DROP IDENTITY;
ALTER TABLE quotations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix invoices table
ALTER TABLE invoices ALTER COLUMN id DROP IDENTITY;
ALTER TABLE invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix payments table
ALTER TABLE payments ALTER COLUMN id DROP IDENTITY;
ALTER TABLE payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix jobs table
ALTER TABLE jobs ALTER COLUMN id DROP IDENTITY;
ALTER TABLE jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix user and other generated tables
ALTER TABLE users ALTER COLUMN id DROP IDENTITY;
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE driver_submissions ALTER COLUMN id DROP IDENTITY;
ALTER TABLE driver_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE rent_to_own_agreements ALTER COLUMN id DROP IDENTITY;
ALTER TABLE rent_to_own_agreements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE rent_to_own_payments ALTER COLUMN id DROP IDENTITY;
ALTER TABLE rent_to_own_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE payment_categories ALTER COLUMN id DROP IDENTITY;
ALTER TABLE payment_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE payment_backdating ALTER COLUMN id DROP IDENTITY;
ALTER TABLE payment_backdating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- ENSURE CRITICAL COLUMNS EXIST
-- ========================================

-- Add driver_id to payments if missing
ALTER TABLE payments ADD COLUMN IF NOT EXISTS driver_id INTEGER;

-- Add payment_type to payments if missing
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_type TEXT DEFAULT 'weekly_cash';

-- Add rent-to-own columns if missing
ALTER TABLE payments ADD COLUMN IF NOT EXISTS rent_to_own_agreement_id BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS is_backdated BOOLEAN DEFAULT FALSE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS backdated_for_date TIMESTAMP;

-- ========================================
-- VERIFY FIXES
-- ========================================

SELECT 'Schema fixes applied successfully!' as status;

-- Check tables
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
