-- BLACKBIRD ERP - Complete Supabase Schema
-- Run this in Supabase SQL Editor
-- This file creates all tables and fixes existing ones

-- ========================================
-- CREATE TABLES WITH PROPER IDENTITY SETTINGS
-- ========================================

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE,
  account_type TEXT,
  role TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DRIVER_SUBMISSIONS TABLE
CREATE TABLE IF NOT EXISTS driver_submissions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  submission_type TEXT NOT NULL,
  submission_data JSONB,
  status TEXT DEFAULT 'pending',
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approved_by BIGINT,
  approved_at TIMESTAMP,
  rejection_reason TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RENT_TO_OWN_AGREEMENTS TABLE
CREATE TABLE IF NOT EXISTS rent_to_own_agreements (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  vehicle_id BIGINT REFERENCES vehicles(id),
  quotation_id BIGINT REFERENCES quotations(id),
  total_amount DECIMAL(12, 2),
  paid_amount DECIMAL(12, 2) DEFAULT 0,
  remaining_balance DECIMAL(12, 2),
  agreement_status TEXT DEFAULT 'Active',
  ownership_transferred BOOLEAN DEFAULT FALSE,
  ownership_transferred_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RENT_TO_OWN_PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS rent_to_own_payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agreement_id BIGINT NOT NULL REFERENCES rent_to_own_agreements(id) ON DELETE CASCADE,
  amount_paid DECIMAL(12, 2),
  payment_date TIMESTAMP,
  recorded_by TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT_CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS payment_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_id BIGINT REFERENCES payments(id) ON DELETE CASCADE,
  driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE,
  category_type TEXT,
  rent_to_own_agreement_id BIGINT REFERENCES rent_to_own_agreements(id),
  amount DECIMAL(12, 2),
  payment_date TIMESTAMP,
  is_backdated BOOLEAN DEFAULT FALSE,
  backdated_for_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT BACKDATING TABLE
CREATE TABLE IF NOT EXISTS payment_backdating (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  payment_date TIMESTAMP NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  category_type TEXT,
  rent_to_own_agreement_id BIGINT REFERENCES rent_to_own_agreements(id),
  description TEXT,
  recorded_by TEXT,
  is_applied BOOLEAN DEFAULT FALSE,
  applied_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- WEBSITE_VISITS TABLE
CREATE TABLE IF NOT EXISTS website_visits (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  page_url TEXT,
  visitor_ip TEXT,
  visited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_agent TEXT,
  referrer TEXT
);

SELECT 'Tables created successfully!' as status;

-- ========================================
-- FIX EXISTING TABLES - Change ID Columns
-- ========================================

-- Fix drivers table
ALTER TABLE drivers ALTER COLUMN id DROP IDENTITY;
ALTER TABLE drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix vehicles table
ALTER TABLE vehicles ALTER COLUMN id DROP IDENTITY;
ALTER TABLE vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix quotations table
ALTER TABLE quotations ALTER COLUMN id DROP IDENTITY;
ALTER TABLE quotations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix invoices table
ALTER TABLE invoices ALTER COLUMN id DROP IDENTITY;
ALTER TABLE invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix payments table
ALTER TABLE payments ALTER COLUMN id DROP IDENTITY;
ALTER TABLE payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix jobs table
ALTER TABLE jobs ALTER COLUMN id DROP IDENTITY;
ALTER TABLE jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix users table
ALTER TABLE users ALTER COLUMN id DROP IDENTITY;
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix driver_submissions table
ALTER TABLE driver_submissions ALTER COLUMN id DROP IDENTITY;
ALTER TABLE driver_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix rent_to_own_agreements table
ALTER TABLE rent_to_own_agreements ALTER COLUMN id DROP IDENTITY;
ALTER TABLE rent_to_own_agreements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix rent_to_own_payments table
ALTER TABLE rent_to_own_payments ALTER COLUMN id DROP IDENTITY;
ALTER TABLE rent_to_own_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix payment_categories table
ALTER TABLE payment_categories ALTER COLUMN id DROP IDENTITY;
ALTER TABLE payment_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix payment_backdating table
ALTER TABLE payment_backdating ALTER COLUMN id DROP IDENTITY;
ALTER TABLE payment_backdating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT 'ID columns fixed!' as status;

-- ========================================
-- ADD MISSING COLUMNS TO EXISTING TABLES
-- ========================================

-- Add missing columns to quotations
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add missing columns to payments
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_type TEXT DEFAULT 'weekly_cash';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS rent_to_own_agreement_id BIGINT REFERENCES rent_to_own_agreements(id);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS is_backdated BOOLEAN DEFAULT FALSE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS backdated_for_date TIMESTAMP;

SELECT 'All missing columns added!' as status;

-- ========================================
-- COMPLETION MESSAGE
-- ========================================

SELECT 'Schema setup complete! All tables ready for use.' as final_status;
